<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE suite SYSTEM "https://testng.org/testng-1.0.dtd">
<suite name="Failed suite [CreditCardSaleRefund]">
  <parameter name="tech" value="woocommerce"/>
  <parameter name="prefix" value="credit.card.sale.refund."/>
  <parameter name="testscenario" value="positive"/>
  <test thread-count="5" name="CreditCardSaleRefund(failed)">
    <classes>
      <class name="com.cybersource.test.woocommerce.CreditCard">
        <methods>
          <include name="executeSaleRefund" invocation-numbers="4 6"/>
          <include name="init"/>
        </methods>
      </class> <!-- com.cybersource.test.woocommerce.CreditCard -->
    </classes>
  </test> <!-- CreditCardSaleRefund(failed) -->
</suite> <!-- Failed suite [CreditCardSaleRefund] -->
