<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE suite SYSTEM "https://testng.org/testng-1.0.dtd">
<suite name="Failed suite [CreditCardSanity]">
  <parameter name="tech" value="woocommerce"/>
  <parameter name="testscenario" value="positive"/>
  <test thread-count="5" name="CreditCardAuth(failed)">
    <parameter name="prefix" value="credit.card.sanity.auth."/>
    <classes>
      <class name="com.cybersource.test.woocommerce.CreditCard">
        <methods>
          <include name="executeAuth" invocation-numbers="0 0 0 0 0 1 1 1 1 1"/>
          <include name="init"/>
        </methods>
      </class> <!-- com.cybersource.test.woocommerce.CreditCard -->
    </classes>
  </test> <!-- CreditCardAuth(failed) -->
  <test thread-count="5" name="CreditCardCaptue(failed)">
    <parameter name="prefix" value="credit.card.sanity.capture."/>
    <classes>
      <class name="com.cybersource.test.woocommerce.CreditCard">
        <methods>
          <include name="init"/>
          <include name="executeAuthCapture" invocation-numbers="0 0 0 0 0 1 1 1 1 1"/>
        </methods>
      </class> <!-- com.cybersource.test.woocommerce.CreditCard -->
    </classes>
  </test> <!-- CreditCardCaptue(failed) -->
</suite> <!-- Failed suite [CreditCardSanity] -->
